defaults:
  - default
  - _self_

histo_dir: IDPerformanceMon/Tracks/SelectedMatchedTracks/Primary
ylabel: "Tail Fraction"
ylim: [0.00001, 0.3]
ratio_ylim: [0.95, 1.09]
rebin: 1
canvas:
  atlas_label:
    y: 0.8
  other_label:
    y: 0.725
  legend:
    y: 0.55

track_latex_names: "d_{0}, z_{0}, q/p_{T}, z_{0}sin#theta, p_{T}"
histograms:
  - histname: ${ex_ctp:"tailfrac_vs_eta_", ${histograms.track_names}}
    xlim: ${gen_list:[-4, 4], 5}
    xlabel: ${gen_list:"#eta^{true}", 5}
    ylabel: ${ex_ctp:"Tail Fraction in ", ${histograms.track_latex_names}}
