histo_dir: IDPerformanceMon/Tracks/SelectedMatchedTracks/Primary
ratio_ylim: [0.75, 1.45]
histograms:
  - histname: "d0resolutionRMS_vs_eta"
    ylim: [2, 300]
    ylabel: "#sigma(d_{0}) [#mum]"
  - histname: "z0resolutionRMS_vs_eta"
    ylim: [10, 100000]
    ylabel: "#sigma(z_{0}) [#mum]"


