defaults:
  - default
  - _self_

histo_dir: IDPerformanceMon/Tracks/SelectedMatchedTracks
ratio_ylim: [0.8, 1.13]
canvas:
  atlas_label:
    y: 0.8
  other_label:
    y: 0.725
  legend:
    y: 0.55

histograms:
  - histname: HitContent_vs_eta_NPixelHits
    ylabel: "N_{hits, Pixel}"
    ylim: [-0.65, 25]
    ratio_ylim: [0.94, 1.065]

  - histname: HitContent_vs_eta_NSCTHits
    ylabel: "N_{hits, Strip}"
    ylim: [-0.65, 20]

  - histname: HitContent_vs_eta_NPixelHoles
    ylabel: "N_{holes, Pixel}"
    ylim: [-0.65, 5]

  - histname: HitContent_vs_eta_NSCTHoles
    ylabel: "N_{holes, Strip}"
    ylim: [0.001, 2]

  - histname: HitContent_vs_eta_NSCTDoubleHoles
    ylabel: "N_{double holes, Strip}"
    ylim: [0.001, 0.25]