# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
# no timing, ${now:%Y-%m-%d}_${now:%H-%M-%S}
run:
  # dir: ${paths.log_dir}/output/${task_name}
  dir: ${paths.log_dir}/output/${task_name}/${hydra.job.override_dirname}

# output directory for sweep runs
sweep:
  dir: ${paths.log_dir}/output/sweeps
  subdir: ${hydra.job.override_dirname}

sweeper:
  params:
    histograms: idpvm_efficiencies, idpvm_hits, idpvm_resolution, idpvm_tailfrac, idpvm_tp